[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'valloric/youcompleteme'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'nlknguyen/papercolor-theme'

[[plugins]]
repo = 'nsf/gocode'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'easymotion/vim-easymotion'
