[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'valloric/youcompleteme'

[[plugins]]
repo = 'tpope/vim-surround'
